model:
  target: ldm.haorui.unet.Unet
  base_learning_rate: 1.0e-05
  params:
    unet_config:
      target: ldm.haorui.resunet.resunetpp.ResUnetPlusPlus
      params:
        channel: 3
    image_scale_01: True

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    wrap: True
    train:
      target: data.haorui.CVC_Clinic.CVC_Clinic_Reconstruction
      params:
        size: 256
        image_path: /home/yixiao/haorui/ccvl15/haorui/datasets/combined_dataset/reduce_data_dataset/CVC_train_images_900.txt
        mask_path: /home/yixiao/haorui/ccvl15/haorui/datasets/combined_dataset/reduce_data_dataset/CVC_train_masks_900.txt
        transpose: True
    validation:
      target: data.haorui.CVC_Clinic.CVC_Clinic_Reconstruction
      params:
        size: 256
        image_path: /home/yixiao/haorui/ccvl15/haorui/datasets/combined_dataset/reduce_data_dataset/CVC_val_images.txt
        mask_path: /home/yixiao/haorui/ccvl15/haorui/datasets/combined_dataset/reduce_data_dataset/CVC_val_masks.txt
        transpose: True

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 200
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    # max_epochs: 2000