model:
  base_learning_rate: 5.0e-07
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    num_timesteps_cond: 1  # all other configs have this set to 1, why
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: condition
    image_size: 32
    channels: 4
    concat_mode: true
    cond_stage_trainable: false
    conditioning_key: concat 
    monitor: val/loss_simple_ema
#    ckpt_path: /home/zongwei/haorui/ccvl15/haorui/latent-diffusion-PC-ccvl23/logs/2023-07-02T02-19-35_ldm_polyp/checkpoints/epoch=000262.ckpt
    scheduler_config:  
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler2
      params:
        warm_up_steps: [200]
        cycle_lengths: [50000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [0.01]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 5  # 4 + 1 (mask)
        out_channels: 4
        model_channels: 128
        attention_resolutions:
        #note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 32 for f8
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_heads: 8
        resblock_updown: true
#        num_head_channels: 32
#        use_spatial_transformer: true
#        transformer_depth: 1
#        context_dim: 512
    first_stage_config: &first_stage_config
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 4
        n_embed: 16384
        ckpt_path: /home/yixiao/haorui/ccvl15/haorui/latent-diffusion-Local/logs/autoencoder/2023-09-30T00-29-21_vqf8_polyp_32x32x4/checkpoints/epoch=000828.ckpt
        ddconfig:
          double_z: false
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 32
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.haorui.cond_stage.OnlyMaskCondStage
      params:
        image_size: 32

          

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    wrap: True
    train:
      target: data.haorui.CVC_Clinic.CVC_Clinic_Reconstruction
      params:
        size: 256
        image_path: /home/yixiao/haorui/ccvl15/haorui/datasets/combined_dataset/reduce_data_dataset/PolypGEN/PolypGEN_p_nonempty_images_train.txt
        mask_path: /home/yixiao/haorui/ccvl15/haorui/datasets/combined_dataset/reduce_data_dataset/PolypGEN/PolypGEN_p_nonempty_masks_train.txt
    validation:
      target: data.haorui.CVC_Clinic.CVC_Clinic_Reconstruction
      params:
        size: 256
        image_path: /home/yixiao/haorui/ccvl15/haorui/datasets/combined_dataset/reduce_data_dataset/PolypGEN/PolypGEN_p_nonempty_images_val.txt
        mask_path: /home/yixiao/haorui/ccvl15/haorui/datasets/combined_dataset/reduce_data_dataset/PolypGEN/PolypGEN_p_nonempty_masks_val.txt


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False
        log_images_kwargs:
          inpaint: False
          plot_diffusion_rows: False
          quantize_denoised: True  # this decides whether to quantize the denoised image. But the non-quanitzed denoised image is still saved 


  trainer:
    benchmark: True
    max_epochs: 2500