model:
  base_learning_rate: 4.5e-6
  target: ldm.haorui.autoencoder.AutoEncoderKL_Polyp
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    ckpt_path: /home/zongwei/haorui/ccvl15/haorui/latent-diffusion-PC-ccvl23/pretrained_ckpts/autoencoder_kl_32x32x4_pretrained.ckpt
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 1
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    wrap: True
    train:
      target: data.haorui.CVC_Clinic.CVC_Clinic_Reconstruction
      params:
        size: 256
        root_path: /home/zongwei/haorui/ccvl15/haorui/datasets/CVC-ClinicDB/PNG
        image_path: /home/zongwei/haorui/ccvl15/haorui/datasets/CVC-ClinicDB/train_image_list.txt
        mask_path: /home/zongwei/haorui/ccvl15/haorui/datasets/CVC-ClinicDB/train_mask_list.txt
    validation:
      target: data.haorui.CVC_Clinic.CVC_Clinic_Reconstruction
      params:
        size: 256
        root_path: /home/zongwei/haorui/ccvl15/haorui/datasets/CVC-ClinicDB/PNG
        image_path: /home/zongwei/haorui/ccvl15/haorui/datasets/CVC-ClinicDB/val_image_list.txt
        mask_path: /home/zongwei/haorui/ccvl15/haorui/datasets/CVC-ClinicDB/val_mask_list.txt

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
